### ISSUE TITLE
Err: Environment has already requested deployment

### ISSUE THREAD

**Issue by jamesscaggs** [twilio-labs/serverless-api#27]
I am unable to deploy to our production environment as of an hour ago. 

Environment:
twilio-cli/1.12.0 darwin-x64 node-v12.14.0

Debug log

```twilio serverless:activate --environment=staging --source-environment=dev -l=debug
Account XXX
Token   e3fe****************************

⠋ Activating build from dev to staging  twilio-serverless-api:builds 
GotError [HTTPError]: Response code 409 (CONFLICT)
  twilio-serverless-api:builds     at EventEmitter.<anonymous> (/Users/jamesscaggs/.twilio-cli/node_modules/got/source/as-promise.js:74:19)
  twilio-serverless-api:builds     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  twilio-serverless-api:builds   name: 'HTTPError',
  twilio-serverless-api:builds   host: undefined,
  twilio-serverless-api:builds   hostname: 'serverless.twilio.com',
  twilio-serverless-api:builds   method: 'POST',
  twilio-serverless-api:builds   path: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-serverless-api:builds   socketPath: undefined,
  twilio-serverless-api:builds   protocol: 'https:',
  twilio-serverless-api:builds   url: 'https://serverless.twilio.com/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-serverless-api:builds   gotOptions: {
  twilio-serverless-api:builds     path: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-serverless-api:builds     protocol: 'https:',
  twilio-serverless-api:builds     hostname: 'serverless.twilio.com',
  twilio-serverless-api:builds     hash: '',
  twilio-serverless-api:builds     search: '',
  twilio-serverless-api:builds     pathname: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-serverless-api:builds     href: 'https://serverless.twilio.com/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-serverless-api:builds     retry: {
  twilio-serverless-api:builds       retries: [Function],
  twilio-serverless-api:builds       methods: [Set],
  twilio-serverless-api:builds       statusCodes: [Set],
  twilio-serverless-api:builds       errorCodes: [Set]
  twilio-serverless-api:builds     },
  twilio-serverless-api:builds     headers: {
  twilio-serverless-api:builds       'user-agent': 'twilio-serverless-api',
  twilio-serverless-api:builds       accept: 'application/json',
  twilio-serverless-api:builds       'accept-encoding': 'gzip, deflate',
  twilio-serverless-api:builds       'content-type': 'application/x-www-form-urlencoded',
  twilio-serverless-api:builds       'content-length': 43
  twilio-serverless-api:builds     },
  twilio-serverless-api:builds     hooks: {
  twilio-serverless-api:builds       beforeError: [],
  twilio-serverless-api:builds       init: [],
  twilio-serverless-api:builds       beforeRequest: [],
  twilio-serverless-api:builds       beforeRedirect: [],
  twilio-serverless-api:builds       beforeRetry: [],
  twilio-serverless-api:builds       afterResponse: []
  twilio-serverless-api:builds     },
  twilio-serverless-api:builds     decompress: true,
  twilio-serverless-api:builds     throwHttpErrors: true,
  twilio-serverless-api:builds     followRedirect: true,
  twilio-serverless-api:builds     stream: false,
  twilio-serverless-api:builds     form: true,
  twilio-serverless-api:builds     json: true,
  twilio-serverless-api:builds     cache: false,
  twilio-serverless-api:builds     useElectronNet: false,
  twilio-serverless-api:builds     baseUrl: [Getter/Setter],
  twilio-serverless-api:builds     auth: 'HIDDEN',
  twilio-serverless-api:builds     body: 'BuildSid=ZB6cc146dcdea9f29332ac536cfebafdc9',
  twilio-serverless-api:builds     method: 'POST'
  twilio-serverless-api:builds   },
  twilio-serverless-api:builds   statusCode: 409,
  twilio-serverless-api:builds   statusMessage: 'CONFLICT',
  twilio-serverless-api:builds   headers: {
  twilio-serverless-api:builds     date: 'Tue, 14 Apr 2020 22:09:59 GMT',
  twilio-serverless-api:builds     'content-type': 'application/json',
  twilio-serverless-api:builds     'content-length': '147',
  twilio-serverless-api:builds     connection: 'close',
  twilio-serverless-api:builds     'twilio-request-id': 'RQ38d75ef6cbb14e2db69726fe4f1b1f14',
  twilio-serverless-api:builds     'twilio-request-duration': '0.031',
  twilio-serverless-api:builds     'access-control-allow-origin': '*',
  twilio-serverless-api:builds     'access-control-allow-headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since',
  twilio-serverless-api:builds     'access-control-allow-methods': 'GET, POST, DELETE, OPTIONS',
  twilio-serverless-api:builds     'access-control-expose-headers': 'ETag',
  twilio-serverless-api:builds     'access-control-allow-credentials': 'true',
  twilio-serverless-api:builds     'x-powered-by': 'AT-5000',
  twilio-serverless-api:builds     'x-shenanigans': 'none',
  twilio-serverless-api:builds     'x-home-region': 'us1',
  twilio-serverless-api:builds     'x-api-domain': 'serverless.twilio.com',
  twilio-serverless-api:builds     'strict-transport-security': 'max-age=31536000'
  twilio-serverless-api:builds   },
  twilio-serverless-api:builds   body: {
  twilio-serverless-api:builds     code: 35002,
  twilio-serverless-api:builds     message: 'Environment already has requested deployment.',
  twilio-serverless-api:builds     more_info: 'https://www.twilio.com/docs/errors/35002',
  twilio-serverless-api:builds     status: 409
  twilio-serverless-api:builds   }
  twilio-serverless-api:builds } +0ms
  ```

```
twilio-run:activate GotError [HTTPError]: Response code 409 (CONFLICT)
  twilio-run:activate     at EventEmitter.<anonymous> (/Users/jamesscaggs/.twilio-cli/node_modules/got/source/as-promise.js:74:19)
  twilio-run:activate     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  twilio-run:activate   name: 'HTTPError',
  twilio-run:activate   host: undefined,
  twilio-run:activate   hostname: 'serverless.twilio.com',
  twilio-run:activate   method: 'POST',
  twilio-run:activate   path: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-run:activate   socketPath: undefined,
  twilio-run:activate   protocol: 'https:',
  twilio-run:activate   url: 'https://serverless.twilio.com/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-run:activate   gotOptions: {
  twilio-run:activate     path: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-run:activate     protocol: 'https:',
  twilio-run:activate     hostname: 'serverless.twilio.com',
  twilio-run:activate     hash: '',
  twilio-run:activate     search: '',
  twilio-run:activate     pathname: '/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-run:activate     href: 'https://serverless.twilio.com/v1/Services/ZS469c3a2e8a838e2d7478d77767f98aa7/Environments/ZE5e76778a6aca9fecb47de2f8b35c8df4/Deployments',
  twilio-run:activate     retry: {
  twilio-run:activate       retries: [Function],
  twilio-run:activate       methods: [Set],
  twilio-run:activate       statusCodes: [Set],
  twilio-run:activate       errorCodes: [Set]
  twilio-run:activate     },
  twilio-run:activate     headers: {
  twilio-run:activate       'user-agent': 'twilio-serverless-api',
  twilio-run:activate       accept: 'application/json',
  twilio-run:activate       'accept-encoding': 'gzip, deflate',
  twilio-run:activate       'content-type': 'application/x-www-form-urlencoded',
  twilio-run:activate       'content-length': 43
  twilio-run:activate     },
  twilio-run:activate     hooks: {
  twilio-run:activate       beforeError: [],
  twilio-run:activate       init: [],
  twilio-run:activate       beforeRequest: [],
  twilio-run:activate       beforeRedirect: [],
  twilio-run:activate       beforeRetry: [],
  twilio-run:activate       afterResponse: []
  twilio-run:activate     },
  twilio-run:activate     decompress: true,
  twilio-run:activate     throwHttpErrors: true,
  twilio-run:activate     followRedirect: true,
  twilio-run:activate     stream: false,
  twilio-run:activate     form: true,
  twilio-run:activate     json: true,
  twilio-run:activate     cache: false,
  twilio-run:activate     useElectronNet: false,
  twilio-run:activate     baseUrl: [Getter/Setter],
  twilio-run:activate     auth: 'xxx:xxx',
  twilio-run:activate     body: 'BuildSid=ZB6cc146dcdea9f29332ac536cfebafdc9',
  twilio-run:activate     method: 'POST'
  twilio-run:activate   },
  twilio-run:activate   statusCode: 409,
  twilio-run:activate   statusMessage: 'CONFLICT',
  twilio-run:activate   headers: {
  twilio-run:activate     date: 'Tue, 14 Apr 2020 22:09:59 GMT',
  twilio-run:activate     'content-type': 'application/json',
  twilio-run:activate     'content-length': '147',
  twilio-run:activate     connection: 'close',
  twilio-run:activate     'twilio-request-id': 'RQ38d75ef6cbb14e2db69726fe4f1b1f14',
  twilio-run:activate     'twilio-request-duration': '0.031',
  twilio-run:activate     'access-control-allow-origin': '*',
  twilio-run:activate     'access-control-allow-headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since',
  twilio-run:activate     'access-control-allow-methods': 'GET, POST, DELETE, OPTIONS',
  twilio-run:activate     'access-control-expose-headers': 'ETag',
  twilio-run:activate     'access-control-allow-credentials': 'true',
  twilio-run:activate     'x-powered-by': 'AT-5000',
  twilio-run:activate     'x-shenanigans': 'none',
  twilio-run:activate     'x-home-region': 'us1',
  twilio-run:activate     'x-api-domain': 'serverless.twilio.com',
  twilio-run:activate     'strict-transport-security': 'max-age=31536000'
  twilio-run:activate   },
  twilio-run:activate   body: {
  twilio-run:activate     code: 35002,
  twilio-run:activate     message: 'Environment already has requested deployment.',
  twilio-run:activate     more_info: 'https://www.twilio.com/docs/errors/35002',
  twilio-run:activate     status: 409
  twilio-run:activate   }
  twilio-run:activate } +0ms
✖ Response code 409 (CONFLICT)
```

**Comment by philnash** [comment]
Hey @jamesscaggs, the error message is right at the end there, it's a 409 with the message "Environment already has requested deployment.". So it sounds like you're trying to activate a build to an environment where you have already activated it. Is that the case?

Also, you probably want to remove this post and [change your auth token](https://support.twilio.com/hc/en-us/articles/223136027-Auth-Tokens-and-How-to-Change-Them) because you have exposed it in this error message.

**Comment by jamesscaggs** [comment]
Thanks for the reply. I edited the post a couple minutes after my initial post and removed the auth token. 

I realize the error code is listed but the documentation link is 404 and I cannot find anyone else with the same issue.  

Also this suddenly happened after I had been successfully deploying all afternoon. 

I waited for a couple hours and tried again and the issue persisted.

**Comment by dkundel** [comment]
Hi @jamesscaggs I just looked at this issue through our support channel and I'm sending you a longer reply there but the issue has to do with the fact that it appears that the build has already been deployed to that particular environment. The error message could be better in this case and give better steps what to do and I'll close this issue in favor of the other one. Thanks for reporting
